# Generated by Django 6.0.7 on 2026-07-29 07:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0005_alter_eventmessage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicSpeaking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "topic",
                    models.TextField(
                        help_text="The question put to the room, e.g. 'What is the worst friendship experience you have ever had?'"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Unticking this closes the room without touching the feature flag.",
                    ),
                ),
                (
                    "anonymous_seed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Randomised starting offset into the anonymous name pool.",
                    ),
                ),
                (
                    "anonymous_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many identities have been handed out so far.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Speaking Discussion",
                "verbose_name_plural": "Public Speaking Discussions",
                "db_table": "public_speaking_discussions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicSpeakingParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_token", models.CharField(db_index=True, max_length=64)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "anonymous_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_speaking_participants",
                        to="events.anonymousname",
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="public_speaking.publicspeaking",
                    ),
                ),
            ],
            options={
                "db_table": "public_speaking_participants",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicSpeakingMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(max_length=1000)),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="public_speaking.publicspeaking",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="public_speaking.publicspeakingparticipant",
                    ),
                ),
            ],
            options={
                "db_table": "public_speaking_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicSpeakingUpvote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvotes",
                        to="public_speaking.publicspeakingmessage",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_upvotes",
                        to="public_speaking.publicspeakingparticipant",
                    ),
                ),
            ],
            options={
                "db_table": "public_speaking_upvotes",
            },
        ),
        migrations.AddConstraint(
            model_name="publicspeakingparticipant",
            constraint=models.UniqueConstraint(
                fields=("discussion", "session_token"),
                name="unique_public_speaking_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicspeakingparticipant",
            constraint=models.UniqueConstraint(
                fields=("discussion", "anonymous_name"),
                name="unique_public_speaking_identity",
            ),
        ),
        migrations.AddIndex(
            model_name="publicspeakingmessage",
            index=models.Index(
                fields=["discussion", "-created_at"],
                name="public_spea_discuss_c8d487_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicspeakingupvote",
            constraint=models.UniqueConstraint(
                fields=("message", "participant"), name="unique_public_speaking_upvote"
            ),
        ),
    ]
