# Generated by Django 6.0.7 on 2026-07-29 07:59

from django.db import migrations, models


def keep_one_message_per_participant(apps, schema_editor):
    """
    Drop pre-existing extra messages so the constraint can be applied.

    Rows predating the one-response rule can have several messages from the
    same participant; the constraint would refuse to build against them. The
    FIRST message each participant sent is the one kept — it is the response
    they actually gave — and any later ones are removed along with their votes
    (cascade), which is the same state the room would be in had the rule always
    been enforced.
    """
    Message = apps.get_model("public_speaking", "PublicSpeakingMessage")

    seen = set()
    doomed = []

    for message in Message.objects.order_by("participant_id", "created_at"):
        if message.participant_id in seen:
            doomed.append(message.pk)
        else:
            seen.add(message.participant_id)

    Message.objects.filter(pk__in=doomed).delete()


class Migration(migrations.Migration):
    # The cleanup deletes rows whose votes cascade, and Postgres refuses to
    # ALTER TABLE while those cascade triggers are still pending in the same
    # transaction. Running non-atomically lets the delete commit first.
    atomic = False

    dependencies = [
        ("public_speaking", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            keep_one_message_per_participant,
            # Nothing to restore going backwards; the deleted rows are gone.
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="publicspeakingmessage",
            constraint=models.UniqueConstraint(
                fields=("participant",), name="one_message_per_participant"
            ),
        ),
    ]
