# Generated by Django 6.0.7 on 2026-07-30 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_eventmessage_content"),
        ("public_speaking", "0002_one_message_per_participant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="publicspeakingparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The authenticated account this identity belongs to. Null only on participants created before login was required.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_speaking_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publicspeakingparticipant",
            name="session_token",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="publicspeakingparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("discussion", "user"),
                name="unique_public_speaking_user_identity",
            ),
        ),
    ]
