"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(DEBUG=(bool, False))

# Read .env file
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
BREVO_API_KEY = env("BREVO_API_KEY")
DEFAULT_FROM_EMAIL = "centagontech@gmail.com"
REDIS_URL = env("REDIS_URL")
MESSAGE_ENCRYPTION_KEY = env("MESSAGE_ENCRYPTION_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])

# ---------------------------------------------------------------------------
# Temporary public speaking mode — one demo session only.
#
# OFF (the default) is today's production behaviour: the public speaking REST
# URLs are never registered and its WebSocket route is never added, so every
# demo path 404s and nothing in the normal product changes. The app stays in
# INSTALLED_APPS so its tables survive the flag flipping back and forth and no
# migration ever has to be rolled back.
# ---------------------------------------------------------------------------
PUBLIC_SPEAKING_MODE = env.bool("PUBLIC_SPEAKING_MODE", default=False)

ACCOUNT_SETUP_TOKEN_LIFETIME = timedelta(minutes=30)

PASSWORD_RESET_TOKEN_LIFETIME = timedelta(minutes=30)

# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework_simplejwt.token_blacklist",
    "rest_framework",
    "drf_spectacular",
    "django_celery_beat",
    # Local apps
    "apps.accounts",
    "apps.users",
    "apps.chat",
    "apps.events",
    "apps.complaints",
    "apps.notifications",
    "apps.administration",
    "apps.presence",
    # Temporary; gated at the URL/routing layer by PUBLIC_SPEAKING_MODE.
    "apps.public_speaking",
]

AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "login": "5/min",
        "check_email": "5/min",
        "logout": "20/hour",
        "set_password": "5/hour",
        "forget_password": "5/hour",
        "reset_password": "5/hour",
        "resend_password_reset": "3/hour",
        "change_password": "5/hour",
        "start_chat": "30/min",
        "report": "5/m",
        "complaint_create": "10/hour",
        "admin_login": "5/m",
        # A dashboard is only reading data and gets opened and refreshed a
        # lot, so the old 5/min ran out after a few clicks.
        "admin_dashboard": "60/min",
        "comment_create": "20/hour",
        "upvote_toggle": "60/hour",
        # Clients with a 30-minute access token need ~2 refreshes an hour;
        # 60 leaves room for many tabs without opening a token-grinding lane.
        "token_refresh": "60/hour",
        "event_create_burst": "3/min",
        "event_create": "10/hour",
        "event_read": "120/min",
        "event_cancel": "10/hour",
        "event_message_create": "20/min",
        "event_membership": "60/hour",
        "chat_end": "30/min",
        "content_update": "60/hour",
        # Public speaking demo (unauthenticated, so scoped by IP).
        # Scoped by IP, and an audience in one hall shares one IP, so these
        # are deliberately generous. Real abuse protection is per-participant:
        # a 2s message cooldown and one message each, both enforced server-side.
        "public_speaking_join": "600/hour",
        "public_speaking": "6000/hour",
    },
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "loggers": {
        "authentication": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "chat": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "public_speaking": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # A stolen refresh token becomes single-use: each refresh call returns a
    # new refresh token and blacklists the old one.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # Embeds a fingerprint of the password in every token; when the password
    # changes, all previously issued tokens are rejected instantly.
    "CHECK_REVOKE_TOKEN": True,
}


# Where the rate limits keep their counts, e.g. "this user has tried to log in
# 4 times in the last minute".

# Database 1, not 0: clearing the cache wipes its whole database, and database
# 0 is where the chat WebSockets and the Celery task queue keep their data.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env(
            "REDIS_CACHE_URL",
            default=f"{REDIS_URL.rsplit('/', 1)[0]}/1",
        ),
    }
}

# The origin prepended to every password-reset / account-setup link (see
# apps.accounts.services.send_account_setup_email / send_password_reset_email,
# both unchanged). An explicit FRONTEND_URL env var always wins; when one
# isn't set, DEBUG — already the environment signal the security-headers
# block above keys off — picks the right default automatically, so a missing
# env var can't send links to the wrong host or crash the app outright.
FRONTEND_URL = env(
    "FRONTEND_URL",
    default="http://localhost:5173" if DEBUG else "https://ekaton.vercel.app",
)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    # redis-py 8.0.0 changed socket_timeout default from None
                    # to 5 seconds. channels_redis issues BZPOPMIN with a 5-second
                    # server-side timeout. The client-side socket fires first, raising
                    # redis.exceptions.TimeoutError and killing every idle WebSocket.
                    # socket_timeout=None restores correct blocking semantics for the
                    # channel layer's long-lived receive connections.
                    "address": env("REDIS_URL"),
                    "socket_timeout": None,
                    "socket_connect_timeout": 5,
                }
            ],
        },
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.AllowAllUsersModelBackend",
]
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        "CONN_MAX_AGE": 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "core.validators.StrongPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:5173", "http://127.0.0.1:5173"]
)
CORS_ALLOW_CREDENTIALS = True

# Public speaking mode identifies its anonymous visitors with a custom request
# header. Any header outside django-cors-headers' small default allowlist makes
# the browser send a CORS preflight, and the preflight is refused unless the
# header is named here — the request then never reaches Django at all. Appended
# only while the flag is on, so production CORS is unchanged.
if PUBLIC_SPEAKING_MODE:
    from corsheaders.defaults import default_headers

    CORS_ALLOW_HEADERS = (*default_headers, "x-speaking-session")

SPECTACULAR_SETTINGS = {
    "TITLE": "Ekaton API",
    "DESCRIPTION": "Production REST API documentation for the Ekaton platform.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
    },
}
# Celery Configuration

CELERY_BROKER_URL = env("REDIS_URL")

CELERY_RESULT_BACKEND = env("REDIS_URL")

CELERY_ACCEPT_CONTENT = ["json"]

CELERY_TASK_SERIALIZER = "json"

CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "end-expired-events-every-minute": {
        "task": "apps.events.tasks.end_expired_events",
        "schedule": crontab(minute="*"),
    },
    # This schedule is the single source of truth for how often the platform
    # seed drifts; apps.presence.seed_services documents the dependency.
    "refresh-platform-seed": {
        "task": "apps.presence.tasks.refresh_platform_seed",
        "schedule": crontab(minute="*/30"),
    },
    # Settles the online count after debounced connect bursts and after
    # presence leases expire. Sends nothing when the count has not moved.
    "reconcile-platform-online-count": {
        "task": "apps.presence.tasks.reconcile_platform_online_count",
        "schedule": 15.0,
    },
}


# Security Headers
# =============================================================================
#
# The HTTPS-dependent settings are gated on DEBUG so local development keeps
# working over plain HTTP. SECURE_PROXY_SSL_HEADER is what lets Django see the
# original scheme when it runs behind a TLS-terminating proxy; without it
# SECURE_SSL_REDIRECT would loop.

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Needed for the Django admin (and any form POST) once the site is on HTTPS.
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
