# Generated by Django 6.0.7 on 2026-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
