# Generated by Django 6.0.7 on 2026-07-30 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_eventmessage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                help_text="The message this one is replying to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="events.eventmessage",
            ),
        ),
        migrations.AddIndex(
            model_name="eventmessage",
            index=models.Index(fields=["reply_to"], name="reply_to_message_idx"),
        ),
    ]
