# Generated by Django 6.0.7 on 2026-07-30 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_eventmessage_reply_to_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="eventmessage",
            name="reply_to_message_idx",
        ),
    ]
