# Generated by Django 6.0.7 on 2026-07-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PasswordResetToken",
            new_name="AccountSetupToken",
        ),
    ]
