# Generated by Django 6.0.7 on 2026-07-28 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_report_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="privatechatroom",
            constraint=models.CheckConstraint(
                condition=models.Q(("user_one", models.F("user_two")), _negated=True),
                name="private_chat_room_distinct_participants",
            ),
        ),
    ]
