# Generated by Django 6.0.7 on 2026-07-31 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_privatechatroom_private_chat_room_distinct_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chat.privatemessage",
            ),
        ),
        migrations.AddIndex(
            model_name="privatemessage",
            index=models.Index(
                fields=["reply_to"], name="private_mes_reply_t_c74582_idx"
            ),
        ),
    ]
