malayalam_words = [
    "Ninde ama, pati!",
    "Aaana kunna",
    "aan-vedi",
    "achante andi",
    "Achinga Kunnan",
    "adichu poli",
    "Ajoli ka Thajoli",
    "ammaudi pootil poocha",
    "Ammente Pooru",
    "amminhnha",
    "Andi pidiyan",
    "anna kunna",
    "Appi",
    "appikunna",
    "Arjun shambu",
    "arraykku chuttum poorruu ullaval",
    "avaraathi",
    "avarathi mone",
    "Beejam",
    "chaka thalayan",
    "chalam nakki",
    "Chandi",
    "Chathavante andi oombiya",
    "Cheekoothi mon",
    "Cheekoothi mone",
    "Chokka lingam",
    "CHotta kunnan",
    "Chotta Tha",
    "coondi",
    "Da patti",
    "Dushtan",
    "eli kunna",
    "Ettukali Patti Pooran",
    "inchi mola",
    "johninte andi",
    "kaatu poori",
    "kallel oouuki",
    "kandara oli",
    "kandi",
    "kandi theeni",
    "Kandu",
    "Kanni",
    "Kanni mola",
    "kara vedi",
    "karim kunna",
    "karim pooran",
    "Karkkidaka vaanam",
    "katta thayoli",
    "kazhappu perutha mairan",
    "Keepu",
    "Kettal",
    "kodam nakiii",
    "Kolekkeri",
    "Koothara",
    "Koothi",
    "Koothichi",
    "kotham",
    "kotham kalakki",
    "kotham nakku",
    "Koyimani",
    "kuch",
    "kulamavuka",
    "kundan",
    "kundaroli poori mone",
    "Kundi",
    "Kundi mon",
    "Kundi oota",
    "kundimol",
    "kunji kunnan",
    "kunna",
    "Kunna",
    "kunna chappu",
    "Kunna Oli",
    "Kunna paal",
    "Kunna thayoli",
    "kunna urunji",
    "kunnappal",
    "kushukk",
    "Lick Me",
    "malayalam",
    "Mandu",
    "Maratel ooki",
    "Masa",
    "Mattanga Poore",
    "matti",
    "Mayiradi mon",
    "Mlechan",
    "mola",
    "moonchikko",
    "Mula Adi",
    "mula chappu",
    "mula kashakku",
    "mula mol",
    "Mundachi",
    "Myir",
    "Myre",
    "Myrru",
    "Naayi meedan",
    "naayinte mone",
    "nayinte mone",
    "Nayinte Mone",
    "Nayinte Monne",
    "ni urru myre",
    "ninde andi maire",
    "Ninte ama koondi ishtima",
    "Ninte ammakku vettu nayinte mone",
    "Ninte ammaku vetu",
    "ninte ammeda tar",
    "Ninte Ammede Kothil.",
    "ninte ammede pooru",
    "Ninte ammede thenga mairu",
    "ninte appante andi",
    "Odu myre",
    "ookki",
    "oomban",
    "oombi mon",
    "Oooomb",
    "Ootan",
    "paara pooru",
    "paareel ookki",
    "Pacha tayolli",
    "Pachila Pooran",
    "Paik keriko myra",
    "paiku vetti",
    "pala thanthakkundaya thaoli",
    "pallinedayil kanthu",
    "pambara kutichi",
    "pampara thayoli",
    "panchavarna kunna",
    "pandi kallan",
    "panniyoli",
    "para andi oomba",
    "Para kutichi",
    "para thayoli punda mon",
    "parii",
    "Paternal andi",
    "pathala poor",
    "patti kantachi mone",
    "patti poori mon",
    "patty theettam",
    "Pazhatoli JanaKi",
    "Pela molichi",
    "Pela vedi",
    "pela vedi kandaroli",
    "petty",
    "Pezhachu Pettavan",
    "poda myre",
    "Poda Thayoli",
    "podda Patti",
    "pola vettu",
    "poochi",
    "Pooranddi",
    "poore ennayil tenni veetil poda",
    "Poori mone",
    "Poorri",
    "Pooru",
    "pooru",
    "Pooru Montha",
    "Pootile mathide mon",
    "poottaavi",
    "poottile mathycurry",
    "poyi ninte kunna oombadaa",
    "poyi oombada",
    "praa thayolli",
    "Puchi",
    "pudti puliyadi",
    "Puh patti",
    "Pulayadi monae",
    "pundachi mone",
    "Purusha Vedi",
    "rainayude poore",
    "Santhosh Pandit",
    "Shandan",
    "Shukla mughan",
    "shuklam dheeni",
    "shuklam nakki",
    "Takkali pooru",
    "Thaayoli",
    "thabala pooran",
    "thakara thayoli",
    "Thallayoli",
    "thalleotha thalleoli",
    "Thalleyoli",
    "thayolee",
    "thayoli",
    "Thayoli",
    "thayoli idli",
    "Thayoli idli",
    "Theetam",
    "theetta moran",
    "theettam",
    "theettathel ookki",
    "Thendi",
    "THENGA MYRE",
    "Thenga pooru",
    "Thevadichi",
    "Thokolli kalla sami",
    "Thukal Kunna",
    "umman",
    "vada",
    "Vadam vali",
    "vali",
    "Vayilitto",
    "vedi",
    "vedi pura",
    "vedi vekkuka",
    "Veppatti",
    "veshya / veshi",
    "vettukili",
    "Viral Iduka",
    "vouvalinu undaya thayoli",
    "fuck",
    "penis",
    "sex",
    "sexy",
    "fucking",
    "asshole",
    "pussy",
    "ass",
    "cock",
    "suck",
    "arsehole",
    "arse",
    "BBC",
    "bbc",
    "BDSM",
    "bdsm",
    "foreplay",
    "doggy",
    "doggystyle",
    "vagina",
    "boobs",
    "boob",
    "booby",
    "boobies",
    "horny",
    "pussies",
    "fucker",
    "bitch",
    "motherfucker",
    "fuckwit",
    "shithead",
    "bastard",
    "son of a bitch",
    "sonofabitch",
    "dickhead",
    "dick",
    "dumbass",
    "twat",
    "douchebag",
    "myr",
    "maire",
    "myren",
    "mair",
    "myrathi",
    "myru",
    "myrr",
    "poor",
    "pooren",
    "poorathi",
    "poorr",
    "pur",
    "puur",
    "puurr",
    "puuren",
    "kodam",
    "andi",
    "kundi",
    "chandi",
    "chandhi",
    "mula",
    "mola",
    "kola",
    "thayoli",
    "tayoli",
    "thalleyoli",
    "annaanpanni",
    "panni",
    "pluck",
    "plucki",
    "plucky",
    "pluckal",
    "kandh",
    "kanth",
    "kanthu",
    "kunna",
    "kunnan",
    "kunne",
    "vedi",
    "vedikal",
    "molakannu",
    "molakann",
    "chukk",
    "chukku",
    "pari",
    "parikal",
    "polayadi",
    "pulayadi",
    "poyalan",
    "pulayan",
    "poori",
    "veshi",
    "veshikal",
    "vediyan",
    "kali theruo",
    "kali tharuo",
    "nayinte mon",
    "nayinte mol",
    "naayinte mone",
    "naayinte mole",
    "karinkunna",
    "cheriya kunna",
    "valya kunna",
    "kuru kunna",
    "arse",
    "arsehole",
    "asshole",
    "bastard",
    "bbc",
    "bdsm",
    "bitch",
    "blowjob",
    "boob",
    "boobies",
    "boobs",
    "booby",
    "cock",
    "cum",
    "cunt",
    "dick",
    "dickhead",
    "doggy",
    "doggystyle",
    "douchebag",
    "dumbass",
    "foreplay",
    "fuck",
    "fucker",
    "fucking",
    "fuckwit",
    "handjob",
    "horny",
    "lick me",
    "motherfucker",
    "penis",
    "prick",
    "pussies",
    "pussy",
    "sex",
    "sexy",
    "shithead",
    "slut",
    "son of a bitch",
    "sonofabitch",
    "suck",
    "twat",
    "vagina",
    "wanker",
    "whore",
    
]